#!/usr/bin/env sh
# Radio Resource Site — NAS installer.
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/JimmyeJones/Radio-Resource-Site/claude/radio-content-web-app-7tby62/install.sh | bash
#
# Environment variables (all optional):
#   RADIO_INSTALL_DIR  Where to clone the repo.            Default: $HOME/radio-resource-site
#   RADIO_DATA_DIR     Where to put SQLite + media on disk.Default: unset (Docker named volumes)
#                      Set this to e.g. /mnt/tank/radio for TrueNAS bind mounts.
#   RADIO_PORT         Host port to expose the web UI.     Default: 3000
#   RADIO_BRANCH       Git branch to install.              Default: claude/radio-content-web-app-7tby62
#   RADIO_REPO         Git URL.                            Default: https://github.com/JimmyeJones/Radio-Resource-Site.git

set -eu

RADIO_INSTALL_DIR="${RADIO_INSTALL_DIR:-$HOME/radio-resource-site}"
RADIO_DATA_DIR="${RADIO_DATA_DIR:-}"
RADIO_PORT="${RADIO_PORT:-3000}"
RADIO_BRANCH="${RADIO_BRANCH:-claude/radio-content-web-app-7tby62}"
RADIO_REPO="${RADIO_REPO:-https://github.com/JimmyeJones/Radio-Resource-Site.git}"

bold=$(printf '\033[1m'); dim=$(printf '\033[2m'); red=$(printf '\033[31m'); green=$(printf '\033[32m'); reset=$(printf '\033[0m')
say()  { printf '%s==>%s %s\n' "$bold" "$reset" "$1"; }
warn() { printf '%s!!%s %s\n' "$red" "$reset" "$1" >&2; }
ok()   { printf '%s ✓%s %s\n' "$green" "$reset" "$1"; }

# --- 1. Sanity checks ----------------------------------------------------------
say "Checking prerequisites"
command -v git >/dev/null 2>&1 || { warn "git not found. Install git and rerun."; exit 1; }
command -v docker >/dev/null 2>&1 || {
  warn "docker not found."
  warn "  TrueNAS SCALE: enable Apps, then SSH in as a user in the docker group."
  warn "  Linux:         https://docs.docker.com/engine/install/"
  exit 1
}
docker compose version >/dev/null 2>&1 || {
  warn "'docker compose' plugin not available. Update Docker Engine to 20.10+ or install docker-compose-plugin."
  exit 1
}
docker info >/dev/null 2>&1 || {
  warn "docker daemon is not reachable for the current user (try sudo, or add yourself to the 'docker' group)."
  exit 1
}

# --- 2. Clone or update --------------------------------------------------------
if [ -d "$RADIO_INSTALL_DIR/.git" ]; then
  say "Updating existing checkout at $RADIO_INSTALL_DIR"
  git -C "$RADIO_INSTALL_DIR" fetch --quiet origin "$RADIO_BRANCH"
  git -C "$RADIO_INSTALL_DIR" checkout --quiet "$RADIO_BRANCH"
  git -C "$RADIO_INSTALL_DIR" pull --ff-only --quiet origin "$RADIO_BRANCH"
elif [ -e "$RADIO_INSTALL_DIR" ]; then
  warn "$RADIO_INSTALL_DIR exists but is not a git checkout. Refusing to overwrite."
  exit 1
else
  say "Cloning $RADIO_REPO ($RADIO_BRANCH) into $RADIO_INSTALL_DIR"
  git clone --quiet --depth 1 --branch "$RADIO_BRANCH" "$RADIO_REPO" "$RADIO_INSTALL_DIR"
fi

cd "$RADIO_INSTALL_DIR"

# --- 3. Generate docker-compose.override.yml ----------------------------------
OVERRIDE="$RADIO_INSTALL_DIR/docker-compose.override.yml"

if [ -n "$RADIO_DATA_DIR" ]; then
  say "Using bind mounts under $RADIO_DATA_DIR"
  mkdir -p "$RADIO_DATA_DIR/data" "$RADIO_DATA_DIR/media"
  cat > "$OVERRIDE" <<EOF
# Generated by install.sh — safe to delete; re-run installer to regenerate.
services:
  web:
    ports:
      - "${RADIO_PORT}:3000"
    volumes:
      - ${RADIO_DATA_DIR}/data:/data
      - ${RADIO_DATA_DIR}/media:/media
  worker:
    volumes:
      - ${RADIO_DATA_DIR}/data:/data
      - ${RADIO_DATA_DIR}/media:/media
EOF
else
  say "Using Docker named volumes (override RADIO_DATA_DIR to bind-mount onto a dataset)"
  if [ "$RADIO_PORT" != "3000" ]; then
    cat > "$OVERRIDE" <<EOF
# Generated by install.sh — safe to delete; re-run installer to regenerate.
services:
  web:
    ports:
      - "${RADIO_PORT}:3000"
EOF
  else
    rm -f "$OVERRIDE"
  fi
fi

# --- 4. Build & start ----------------------------------------------------------
say "Building and starting containers (this is slow the first time)"
docker compose up -d --build --pull missing

# --- 5. Wait for ready ---------------------------------------------------------
say "Waiting for the web service to become ready"
URL="http://localhost:${RADIO_PORT}"
i=0
until curl -fsS "${URL}/api/jobs" >/dev/null 2>&1; do
  i=$((i + 1))
  if [ "$i" -gt 30 ]; then
    warn "Service didn't come up in 60 s. Recent logs:"
    docker compose logs --tail 40 web || true
    exit 1
  fi
  sleep 2
done

ok "Radio Resource Site is up."
printf '\n'
printf '  %sOpen:%s %s%s%s\n' "$bold" "$reset" "$green" "$URL" "$reset"
printf '  %sLogs:%s     %sdocker compose -f %s/docker-compose.yml logs -f%s\n' "$bold" "$reset" "$dim" "$RADIO_INSTALL_DIR" "$reset"
printf '  %sStop:%s     %sdocker compose -f %s/docker-compose.yml down%s\n' "$bold" "$reset" "$dim" "$RADIO_INSTALL_DIR" "$reset"
printf '  %sUpdate:%s   %scurl -fsSL https://raw.githubusercontent.com/JimmyeJones/Radio-Resource-Site/%s/install.sh | bash%s\n' "$bold" "$reset" "$dim" "$RADIO_BRANCH" "$reset"
printf '\n'
if [ -n "$RADIO_DATA_DIR" ]; then
  printf '  Data lives at: %s\n' "$RADIO_DATA_DIR"
fi
