import { describe, it, expect } from 'vitest';
import { parseAdif, toAdif, adifDateToUnix } from '@/lib/adif';

describe('ADIF', () => {
  it('round-trips a QSO', () => {
    const adif = toAdif([
      { callsign: 'W1AW', qsoAt: adifDateToUnix('20240115', '1430'), band: '20m', mode: 'SSB', rstSent: '59', rstRcvd: '57', country: 'United States' },
    ]);
    const parsed = parseAdif(adif);
    expect(parsed).toHaveLength(1);
    expect(parsed[0].call).toBe('W1AW');
    expect(parsed[0].band).toBe('20m');
    expect(parsed[0].mode).toBe('SSB');
    expect(parsed[0].rst_sent).toBe('59');
  });

  it('parses a typical exported record with header', () => {
    const text = `Generated by X\n<ADIF_VER:5>3.1.4<EOH>\n<CALL:5>K6UDA<QSO_DATE:8>20231201<TIME_ON:4>0102<BAND:3>40m<MODE:2>CW<EOR>`;
    const recs = parseAdif(text);
    expect(recs).toHaveLength(1);
    expect(recs[0].call).toBe('K6UDA');
    expect(recs[0].band).toBe('40m');
  });

  it('adifDateToUnix decodes a date/time', () => {
    const u = adifDateToUnix('20240115', '1430');
    const d = new Date(u * 1000);
    expect(d.getUTCFullYear()).toBe(2024);
    expect(d.getUTCMonth()).toBe(0);
    expect(d.getUTCDate()).toBe(15);
    expect(d.getUTCHours()).toBe(14);
  });
});
